[server]
# Optimisations pour les performances
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
# Optimisations pour le navigateur
gatherUsageStats = false

[client]
# Optimisations pour le client
showErrorDetails = false

[theme]
# Thème optimisé
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 